name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main # only trigger on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/taskweb
            git pull origin main
            docker stop flask-tasks || true
            docker rename flask-tasks flask-tasks_backup || true

            # Step 2: Build new image
            docker build -t flask-tasks .

            # Step 3: Run the new container
            docker run -d -p 5000:5000 --name flask-tasks flask-tasks

            # Step 4: Wait a few seconds and test if it's healthy
            sleep 5
            if ! curl -sSf http://localhost:5000/health > /dev/null; then
              echo "New container failed, rolling back..."
              docker stop flask-tasks
              docker rm flask-tasks
              docker rename flask-tasks_backup flask-tasks
              docker start flask-tasks
              exit 1
            else
              echo "New container running successfully. Removing backup."
              docker rm flask-tasks_backup || true
              docker image prune -f
            fi
